language: objective-c # swift
osx_image: xcode9.2

# Xcode Configuration
xcode_workspace: SpotifyKit.xcworkspace
# xcode_project: SpotifyKit.xcodeproj
xcode_scheme: SpotifyKit

# Build Lifecycle
before_install:
    # - brew update # https://docs.travis-ci.com/user/reference/osx/#Homebrew
    # - brew install carthage
    - brew outdated carthage || brew upgrade carthage
# install:
before_script:
    - carthage bootstrap --no-build # checks out the Spotify iOS SDK
# script:
# before_cache:  # OPTIONAL (for cleaning up cache)
# after_success: # OR after_failure:
# before_deploy: # OPTIONAL
# deploy:        # OPTIONAL
# after_deploy:  # OPTIONAL
# after_script:

# Caching
cache:
    directories:
    - Carthage

# Safelist
branches:
    only:
    - master
    - stable

# Blocklist
# branches:
#     except:
#     - /^feature-.*$/
#     - /^hotfix-.*$/
